archetype.groupId=mongodb.example
archetype.artifactId=springboot-arquetype
archetype.package=mongodb.example.ca
archetype.version=0.0.1
## groupId por defecto para proyectos generados a partir de este arquetipo
groupId=com.example
## artifactId por defecto para proyectos generados a partir de este arquetipo
artifactId=com.example